config/routes.rb
Rails.application.routes.draw do
  get 'quotes/new'
  get 'welcome/index'

  resources :quotes do
  	resources :comments
  end
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :quote
end

app/models/quote.rb
class Quote < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :Enter_your_quote, presence: true,
								 length: {minimum: 5, maximum: 2000}
	validates :Email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
	include ActionController::HttpAuthentication::Basic::ControllerMethods
	include ActionController::HttpAuthentication::Digest::ControllerMethods
	include ActionController::HttpAuthentication::Token::ControllerMethods
	include ActionController::MimeResponds
	include ActionController::RequestForgeryProtection

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	
	def create
		@quote = Quote.find(params[:quote_id])
		@comment = @quote.comments.create(comment_params)
		redirect_to quote_path(@quote)
	end

	def destroy
		@quote = Quote.find(params[:quote_id])
		@comment = @quote.comments.find(params[:id])
		@comment.destroy
		redirect_to quote_path(@quote) #show path
	end



	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController


  def index
  	@quotes = Quote.all
  	render json: @quotes, status: :ok
  end

  def new
  	@quote = Quote.new
  end

  def edit
  	@quote = Quote.find(params[:id])
  end

  def create
  	 @quote = Quote.new(quotes_params)

      respond_to do |format|
        if @quote.save
          UserMailer.with(quote: @quote).practice_email.deliver_now!

          format.html{ redirect_to(@quote, notice: 'Quote was successfully created')}
          format.json{ render json: @quote, status: :created, location: @quote}

        else
          format.html { render action: 'new'}
          format.json {render json: @quote.errors, status: :unprocessable_entity}

        end
      end
  end

  def show
  	@quote = Quote.find(params[:id])
    render json: @quote, status: :ok
  end

  def update
  	@quote = Quote.find(params[:id])

  	 respond_to do |format|
      if @quote.update(quotes_params)
        UserMailer.with(quote: @quote).update_email.deliver_now!

          format.html{ redirect_to(@quote, notice: 'Quote was successfully edited')}
          format.json{ render json: @quote, status: :edited, location: @quote}

        else
          format.html { render action: 'new'}
          format.json {render json: @quote.errors, status: :unprocessable_entity}

        end
      #redirect_to quotes_path (index path)
    end
  end

  def destroy
  	@quote = Quote.find(params[:id])

    respond_to do |format|
  	 if @quote.destroy
      UserMailer.with(quote: @quote).destroy_email.deliver_now!

          format.html{ redirect_to(@quote, notice: 'Quote was successfully created')}
          format.json{ render json: @quote, status: :deleted, location: @quote}

        else
          format.html { render action: 'new'}
          format.json {render json: @quote.errors, status: :unprocessable_entity}

        end
      #redirect_to quotes_path (index path)
    end
  end
    
  

  private
  	def quotes_params
  		params.require(:quote).permit(:Enter_your_quote, :Written_by, :Email)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/quote_helper.rb
module QuoteHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
	<p>
		<strong>Commenter:</strong>
		<%= comment.commenter %>
	</p>
	<p>
		<strong>Comment:</strong>
		<%= comment.body %>
	</p>

	<p>
		<%= link_to 'Destroy Comment' , [comment.quote , comment],
			method: :delete,
			data: { confirm: 'Are you sure?'} %>
	</p>

app/views/comments/_form.html.erb
<%= form_with(model: [@quote, @quote.comments.build], local: true) do |com_form| %>
	<p>
		<%= com_form.label :commenter %><br>
		<%= com_form.text_field :commenter %>
	</p>
	<p>
		<%= com_form.label :body %><br>
		<%= com_form.text_area :body %>
	</p>
	<p>
		<%= com_form.submit "Post" %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Getstart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with model: @quote, local: true do |f| %>

  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@quote.errors.count, "error") %> This Submission can't be saved:
      </h2>
      <ul>
        <% @quote.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
	
  <p>
		<%= f.label :Enter_your_quote %>
	</p>
	<p>
		<%= f.text_area :Enter_your_quote, size: "60x12" %>
	</p>
	<p>
		<%= f.label :Written_by %>
		<%= f.text_field :Written_by %>
	</p>
	<p>
		<%= f.submit "Create" %>
	</p>
<% end %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/edit.html.erb
<h1>Edit page</h1>

<%= render 'form' %>

app/views/quotes/index.html.erb
<h1>Getting started </h1>
<%= link_to 'My Blog', controller: 'quotes'%>
<%= link_to 'New', new_quote_path %>
<table>
	<tr>
		<th>Quote</th>
		<th>Author</th>
	</tr>
	 
	<% @quotes.each do |list| %>
		<tr>
			<td><%= list.Enter_your_quote %></td>
			<td><%= list.Written_by %></td>
			<td><%= link_to "Show", quote_path(list) %></td>
			<td><%= link_to "Edit", edit_quote_path(list) %></td>
			<td><%= link_to 'Destroy', quote_path(list),
					method: :delete,
					data: {confirm: "Are you sure?"}%></td>
		</tr>
	<% end %>
</table>

app/views/quotes/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>
 

app/views/quotes/show.html.erb
<table>
	<tr>
		<th>Quote</th>
		<th>Author</th>
	</tr>

		<tr>
			<td><%= @quote.Enter_your_quote %></td>
			<td><%= @quote.Written_by %></td>
		</tr>
</table>

<h3>Comments</h3>
	<%= render @quote.comments %>

<h2>Add a comment:</h2>
	<%= render 'comments/form' %>

<%= link_to 'Edit', edit_quote_path(@quote) %>
<%= link_to 'Back', quotes_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>